// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1X-emEk0EwDvWJxrSqay13OUumvDEd4',
    appId: '1:1076558884193:web:ce06e91063de083f6aa920',
    messagingSenderId: '1076558884193',
    projectId: 'boxmon',
    authDomain: 'boxmon.firebaseapp.com',
    storageBucket: 'boxmon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6JndjeqllozQYeB17KRM6_gNylDyROc',
    appId: '1:1076558884193:android:6f4f0535dc99b9726aa920',
    messagingSenderId: '1076558884193',
    projectId: 'boxmon',
    storageBucket: 'boxmon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03AMQW3O_mplBmr-JcPVGwy4iNC8ak2s',
    appId: '1:1076558884193:ios:3dc0403dcb0f1a086aa920',
    messagingSenderId: '1076558884193',
    projectId: 'boxmon',
    storageBucket: 'boxmon.firebasestorage.app',
    iosBundleId: 'com.example.boxmon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC03AMQW3O_mplBmr-JcPVGwy4iNC8ak2s',
    appId: '1:1076558884193:ios:3dc0403dcb0f1a086aa920',
    messagingSenderId: '1076558884193',
    projectId: 'boxmon',
    storageBucket: 'boxmon.firebasestorage.app',
    iosBundleId: 'com.example.boxmon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1X-emEk0EwDvWJxrSqay13OUumvDEd4',
    appId: '1:1076558884193:web:7a0a4373213a70896aa920',
    messagingSenderId: '1076558884193',
    projectId: 'boxmon',
    authDomain: 'boxmon.firebaseapp.com',
    storageBucket: 'boxmon.firebasestorage.app',
  );
}
